server:
  port:   8081

spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/example_db?serverTimezone=Mexico/General
    username: root
    password: root1234
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.diaclect.MySQLDialect