microservice1:
  image: 'poc/demo:latest'
  expose:
    - "8080"
microservice2:
  image: 'poc/demo:latest'
  expose:
    - "8080"
loadbalancer:
  image: 'dockercloud/haproxy:latest'
  links:
    - microservice1
    - microservice2
  ports:
    - '80:80'
